# Generated by Django 5.2.8 on 2025-12-21 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_blog_alter_upvote_unique_together_comment_blog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AI_Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('category', models.CharField(choices=[('productivity', 'Productivity'), ('design', 'Design'), ('development', 'Development'), ('writing', 'Writing'), ('marketing', 'Marketing'), ('education', 'Education'), ('health', 'Health'), ('finance', 'Finance'), ('other', 'Other')], max_length=20)),
                ('upvotes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tools', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='problems.tag')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='comment',
            name='ai_tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='problems.ai_tool'),
        ),
        migrations.AddField(
            model_name='upvote',
            name='ai_tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upvotes_by_users', to='problems.ai_tool'),
        ),
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together={('user', 'problem', 'solution', 'blog', 'ai_tool')},
        ),
    ]
